import React from 'react'
import appwriteService from "../appwrite/config"
import {Link} from "react-router-dom"

// $id is the unique document ID generated by Appwrite
// Appwrite system fields start with "$" to indicate metadata

function Postcard({
  $id,           // unique post ID used for routing
  title,         // post title displayed on card
  featuredImage, // image file ID stored in Appwrite
}) {

  // Link navigates to the full post page using the post ID
  // Example route: /post/6548732
  <Link to={`/post/${$id}`}>

  // Card container styling
  // w-full      → full width
  // bg-gray-100 → light background
  // rounded-xl  → rounded corners
  // p-4         → padding inside card
  <div className='w-full bg-gray-100 rounded-xl p-4'>

    // Image wrapper
    // mb-4 → space below image
    <div className='w-full justify-center mb-4'>

      // Image preview fetched from Appwrite storage
      // featuredImage → file ID
      <img
        src={appwriteService.getFilePreview(featuredImage)}
        alt={title}
        className='rounded-xl' // rounded image corners
      />

    </div>

    // Post title styling
    // text-xl  → larger text
    // font-bold → bold title
    <h2 className='text-xl font-bold'>
      {title}
    </h2>

  </div>
}