import React from 'react'
import appwriteService from "../appwrite/config"
import {Link} from "react-router-dom"

// $id is the unique document ID generated by Appwrite
// Appwrite system fields start with "$" to indicate metadata

function Postcard({
  $id,           
  title,         
  featuredImage, 
}) {

  return(

    // Link navigates to the full post page using the specific post ID
    // Example route: /post/6548732
  <Link to={`/post/${$id}`}>

    // Card container styling
  <div className='w-full bg-gray-100 rounded-xl p-4'>

      // Image wrapper
    <div className='w-full justify-center mb-4'>

     // Image preview fetched from Appwrite storage(bucket)
    // featuredImage → file ID
      <img
        src={appwriteService.getFilePreview(featuredImage)}
        alt={title}
        className='rounded-xl' 
      />

    </div>
    
    // Post title styling
    <h2 className='text-xl font-bold'>
      {title}
    </h2>

  </div>
  </Link>
  )
}

export default Postcard


